# Generated by Django 4.2.17 on 2025-01-09 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=100)),
                ('bean', models.CharField(choices=[('arabica', 'Arabica'), ('robusta', 'Robusta'), ('liberica', 'Liberica')], max_length=10)),
                ('taste_profile', models.TextField()),
                ('roast', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('dark', 'Dark')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_coffees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
