# Generated by Django 4.2.17 on 2025-01-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_coffee_listing_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffee',
            options={'ordering': ['vendor', 'coffee_name']},
        ),
        migrations.RenameField(
            model_name='coffee',
            old_name='name',
            new_name='coffee_name',
        ),
    ]
