# Generated by Django 4.2.17 on 2025-01-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_vendorabout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorabout',
            name='about',
            field=models.TextField(),
        ),
    ]
