# Generated by Django 4.2.17 on 2025-01-20 11:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_alter_vendorabout_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='product_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
