# Generated by Django 4.2.17 on 2025-01-20 12:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_coffee_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='product_image',
            field=cloudinary.models.CloudinaryField(default='default', max_length=255, verbose_name='image'),
        ),
    ]
