# Generated by Django 4.2.17 on 2025-01-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_alter_coffee_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='bean',
            field=models.CharField(choices=[('arabica', 'Arabica'), ('excelsa', 'Excelsa'), ('robusta', 'Robusta'), ('liberica', 'Liberica')], max_length=30),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='roast',
            field=models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('dark', 'Dark')], max_length=30),
        ),
    ]
